### ISSUE TITLE
versioning follow @enhance/ssr

### ISSUE THREAD

**Issue by tbeseda** [enhance-dev/types#3]
I think this might be one of those rare cases where 2 libraries versions should match

thoughts?

**Comment by kristoferjoseph** [comment]
😬 
Matching versions has never worked out for me in the past, but neither has Typescripts so let's do it!

**Comment by tbeseda** [comment]
ugh yeah you're right, it rarely works. because you need to maintain it with each Enhance release even if the types **_don't_** change. Which... they probably won't move that much at all.
So I'm kinda rethinking this idea.

**Comment by tbeseda** [comment]
I'm against this for now. reopen if we find it could be helpful
